name: Lint

on:
  push:
    branches:
      - main
      - dv_schedule
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Install Python Dependencies
        run: pip install black==24.4.0 flake8==7.0.0

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          black_args: "-l88"
          black_auto_fix: true
          flake8: true
          flake8_args: "--max-line-length=100 --ignore=E203"